### ISSUE TITLE
Does this support windows XP?

### ISSUE THREAD

**Issue by taeguk** [avast-tl/fileformat#3]
There is no exact descriptions for supporting OS/platforms.
After generating VS files for Visual Studio 2015 Update 3, I found that projects use v140 instead of v140_xp for platform toolset.
If I change the platform toolset from vc140 to vc140_xp, I can use this library in windows XP?
(Note that there are some issues in vc140_xp like C++11 magic statics and TLS.)

**Comment by s3rvac** [comment]
Officially, we support only Windows 7 or later. The reason is that [LLVM](https://llvm.org/) supports [only Windows 7 or later](http://releases.llvm.org/3.8.0/docs/ReleaseNotes.html#non-comprehensive-list-of-changes-in-this-release):

> Since LLVM 3.8, the minimum Windows version required for running LLVM is Windows 7. Earlier versions, including Windows Vista and XP are no longer supported.

So, you can try the build on Windows XP, but we unfortunately cannot guarantee that it will work.
